# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'youtube.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from chess import *
from PyQt5 import QtCore, QtGui, QtWidgets
# from PyQt5.QtCore import everything
from PyQt5.QtGui import *

import sys
from PyQt5.QtWidgets import QGraphicsItem
from PyQt5.QtWidgets import QMainWindow
from PyQt5.QtWidgets import *
# We are importing our generated python file .py

# We are using time for the splash screen in action
import time
from PyQt5.QtCore import (QFileInfo, QTimer)
from PyQt5.QtGui import (QImage)
from PyQt5.QtCore import (QByteArray, QDataStream, QIODevice, QMimeData,
                          QPoint, Qt)
from PyQt5.QtGui import QColor, QDrag, QPainter, QPixmap
from PyQt5.QtWidgets import QApplication, QFrame, QLabel
import time


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(882, 619)
        MainWindow.setAcceptDrops(True)
        self.list_values_x = [10, 80, 150, 220, 290, 360, 430, 500]
        self.list_values_y = [20, 90, 160, 230, 300, 370, 440, 510]
        # self.setStyleSheet("background-image: url(:/back.png);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget_9 = QtWidgets.QWidget(self.centralwidget)
        self.widget_9.setGeometry(QtCore.QRect(290, 20, 71, 71))
        self.widget_9.setAcceptDrops(True)
        self.widget_9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_9.setObjectName("widget_9")

        self.check_box = QtWidgets.QCheckBox(self)
        self.check_box.setGeometry(QtCore.QRect(620, 80, 60, 20))
        self.check_box.setText('queen')

        self.check_box1 = QtWidgets.QCheckBox(self)
        self.check_box1.setGeometry(QtCore.QRect(620, 110, 60, 20))
        self.check_box1.setText('bishop')

        self.check_box2 = QtWidgets.QCheckBox(self)
        self.check_box2.setGeometry(QtCore.QRect(620, 140, 60, 20))
        self.check_box2.setText('knight')

        self.check_box3 = QtWidgets.QCheckBox(self)
        self.check_box3.setGeometry(QtCore.QRect(620, 170, 60, 20))
        self.check_box3.setText('rook')

        self.clock = QtWidgets.QLCDNumber(self)
        self.clock.setGeometry(QtCore.QRect(640, 230, 100, 50))
        self.clock.setStyleSheet("background-color: rgb(155, 155, 255);")

        self.clock.setObjectName("black_king_icon")

        self.button = QtWidgets.QPushButton(self)
        self.button.setGeometry(QtCore.QRect(640, 370, 100, 50))
        self.button.setText('RESET')
        self.button.setStyleSheet('font: Arial;')
        self.button.setStyleSheet("background-color: rgb(155, 155, 255);")

        self.button_switch = QtWidgets.QPushButton(self)
        self.button_switch.setGeometry(QtCore.QRect(640, 440, 100, 50))
        self.button_switch.setText('SWITCH')
        self.button_switch.setStyleSheet('font: Arial;')
        self.button_switch.setStyleSheet("background-color: rgb(155, 155, 255);")

        # self.button.setStyleSheet("border - color: rgb(0, 255, 255);")
        self.widget_10 = QtWidgets.QWidget(self.centralwidget)
        self.widget_10.setGeometry(QtCore.QRect(430, 20, 71, 71))
        self.widget_10.setAcceptDrops(True)
        self.widget_10.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_10.setObjectName("widget_10")

        self.widget_11 = QtWidgets.QWidget(self.centralwidget)
        self.widget_11.setGeometry(QtCore.QRect(80, 20, 71, 71))
        self.widget_11.setAcceptDrops(True)
        self.widget_11.setStyleSheet("background-image: url(:/background.png);")
        self.widget_11.setObjectName("widget_11")

        self.widget_12 = QtWidgets.QWidget(self.centralwidget)
        self.widget_12.setGeometry(QtCore.QRect(220, 20, 71, 71))
        self.widget_12.setAcceptDrops(True)
        self.widget_12.setStyleSheet("background-image: url(:/background.png);")
        self.widget_12.setObjectName("widget_12")

        self.widget_13 = QtWidgets.QWidget(self.centralwidget)
        self.widget_13.setGeometry(QtCore.QRect(150, 20, 71, 71))
        self.widget_13.setAcceptDrops(True)
        self.widget_13.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_13.setObjectName("widget_13")

        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(10, 20, 71, 71))
        self.widget1.setAcceptDrops(True)
        self.widget1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget1.setObjectName("widget1")

        self.widget_15 = QtWidgets.QWidget(self.centralwidget)
        self.widget_15.setGeometry(QtCore.QRect(500, 20, 71, 71))
        self.widget_15.setAcceptDrops(True)
        self.widget_15.setStyleSheet("background-image: url(:/background.png);")
        self.widget_15.setObjectName("widget_15")

        self.widget_16 = QtWidgets.QWidget(self.centralwidget)
        self.widget_16.setGeometry(QtCore.QRect(360, 20, 71, 71))
        self.widget_16.setAcceptDrops(True)
        self.widget_16.setStyleSheet("background-image: url(:/background.png);")
        self.widget_16.setObjectName("widget_16")

        self.widget_35 = QtWidgets.QWidget(self.centralwidget)
        self.widget_35.setGeometry(QtCore.QRect(80, 90, 71, 71))
        self.widget_35.setAcceptDrops(True)
        self.widget_35.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_35.setObjectName("widget_35")

        self.widget_38 = QtWidgets.QWidget(self.centralwidget)
        self.widget_38.setGeometry(QtCore.QRect(10, 90, 71, 71))
        self.widget_38.setAcceptDrops(True)
        self.widget_38.setStyleSheet("background-image: url(:/background.png);")
        self.widget_38.setObjectName("widget_38")

        self.widget_39 = QtWidgets.QWidget(self.centralwidget)
        self.widget_39.setGeometry(QtCore.QRect(150, 90, 71, 71))
        self.widget_39.setAcceptDrops(True)
        self.widget_39.setStyleSheet("background-image: url(:/background.png);")
        self.widget_39.setObjectName("widget_39")

        self.widget_36 = QtWidgets.QWidget(self.centralwidget)
        self.widget_36.setGeometry(QtCore.QRect(220, 90, 71, 71))
        self.widget_36.setAcceptDrops(True)
        self.widget_36.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_36.setObjectName("widget_36")

        self.widget_37 = QtWidgets.QWidget(self.centralwidget)
        self.widget_37.setGeometry(QtCore.QRect(360, 90, 71, 71))
        self.widget_37.setAcceptDrops(True)
        self.widget_37.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_37.setObjectName("widget_37")

        self.widget_40 = QtWidgets.QWidget(self.centralwidget)
        self.widget_40.setGeometry(QtCore.QRect(290, 90, 71, 71))
        self.widget_40.setAcceptDrops(True)
        self.widget_40.setStyleSheet("background-image: url(:/background.png);")
        self.widget_40.setObjectName("widget_40")

        self.widget_41 = QtWidgets.QWidget(self.centralwidget)
        self.widget_41.setGeometry(QtCore.QRect(500, 90, 71, 71))
        self.widget_41.setAcceptDrops(True)
        self.widget_41.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_41.setObjectName("widget_41")

        self.widget_42 = QtWidgets.QWidget(self.centralwidget)
        self.widget_42.setGeometry(QtCore.QRect(430, 90, 71, 71))
        self.widget_42.setAcceptDrops(True)
        self.widget_42.setStyleSheet("background-image: url(:/background.png);")
        self.widget_42.setObjectName("widget_42")

        self.widget_43 = QtWidgets.QWidget(self.centralwidget)
        self.widget_43.setGeometry(QtCore.QRect(500, 230, 71, 71))
        self.widget_43.setAcceptDrops(True)
        self.widget_43.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_43.setObjectName("widget_43")
        self.widget_17 = QtWidgets.QWidget(self.centralwidget)
        self.widget_17.setGeometry(QtCore.QRect(430, 160, 71, 71))
        self.widget_17.setAcceptDrops(True)
        self.widget_17.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_17.setObjectName("widget_17")
        self.widget_18 = QtWidgets.QWidget(self.centralwidget)
        self.widget_18.setGeometry(QtCore.QRect(220, 160, 71, 71))
        self.widget_18.setAcceptDrops(True)
        self.widget_18.setStyleSheet("background-image: url(:/background.png);")
        self.widget_18.setObjectName("widget_18")
        self.widget_19 = QtWidgets.QWidget(self.centralwidget)
        self.widget_19.setGeometry(QtCore.QRect(360, 160, 71, 71))
        self.widget_19.setAcceptDrops(True)
        self.widget_19.setStyleSheet("background-image: url(:/background.png);")
        self.widget_19.setObjectName("widget_19")
        self.widget_44 = QtWidgets.QWidget(self.centralwidget)
        self.widget_44.setGeometry(QtCore.QRect(80, 230, 71, 71))
        self.widget_44.setAcceptDrops(True)
        self.widget_44.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_44.setObjectName("widget_44")
        self.widget_20 = QtWidgets.QWidget(self.centralwidget)
        self.widget_20.setGeometry(QtCore.QRect(80, 160, 71, 71))
        self.widget_20.setAcceptDrops(True)
        self.widget_20.setStyleSheet("background-image: url(:/background.png);")
        self.widget_20.setObjectName("widget_20")
        self.widget_45 = QtWidgets.QWidget(self.centralwidget)
        self.widget_45.setGeometry(QtCore.QRect(290, 230, 71, 71))
        self.widget_45.setAcceptDrops(True)
        self.widget_45.setStyleSheet("background-image: url(:/background.png);")
        self.widget_45.setObjectName("widget_45")

        self.widget_21 = QtWidgets.QWidget(self.centralwidget)
        self.widget_21.setGeometry(QtCore.QRect(150, 160, 71, 71))
        self.widget_21.setAcceptDrops(True)
        self.widget_21.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_21.setObjectName("widget_21")
        self.widget_46 = QtWidgets.QWidget(self.centralwidget)
        self.widget_46.setGeometry(QtCore.QRect(430, 230, 71, 71))
        self.widget_46.setAcceptDrops(True)
        self.widget_46.setStyleSheet("background-image: url(:/background.png);")
        self.widget_46.setObjectName("widget_46")
        self.widget_22 = QtWidgets.QWidget(self.centralwidget)
        self.widget_22.setGeometry(QtCore.QRect(500, 160, 71, 71))
        self.widget_22.setAcceptDrops(True)
        self.widget_22.setStyleSheet("background-image: url(:/background.png);")
        self.widget_22.setObjectName("widget_22")
        self.widget_47 = QtWidgets.QWidget(self.centralwidget)
        self.widget_47.setGeometry(QtCore.QRect(10, 230, 71, 71))
        self.widget_47.setAcceptDrops(True)
        self.widget_47.setStyleSheet("background-image: url(:/background.png);")
        self.widget_47.setObjectName("widget_47")
        self.widget_23 = QtWidgets.QWidget(self.centralwidget)
        self.widget_23.setGeometry(QtCore.QRect(290, 160, 71, 71))
        self.widget_23.setAcceptDrops(True)
        self.widget_23.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_23.setObjectName("widget_23")
        self.widget_48 = QtWidgets.QWidget(self.centralwidget)
        self.widget_48.setGeometry(QtCore.QRect(150, 230, 71, 71))
        self.widget_48.setAcceptDrops(True)
        self.widget_48.setStyleSheet("background-image: url(:/background.png);")
        self.widget_48.setObjectName("widget_48")
        self.widget_49 = QtWidgets.QWidget(self.centralwidget)
        self.widget_49.setGeometry(QtCore.QRect(360, 230, 71, 71))
        self.widget_49.setAcceptDrops(True)
        self.widget_49.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_49.setObjectName("widget_49")
        self.widget_50 = QtWidgets.QWidget(self.centralwidget)
        self.widget_50.setGeometry(QtCore.QRect(220, 230, 71, 71))
        self.widget_50.setAcceptDrops(True)
        self.widget_50.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_50.setObjectName("widget_50")
        self.widget_24 = QtWidgets.QWidget(self.centralwidget)
        self.widget_24.setGeometry(QtCore.QRect(10, 160, 71, 71))
        self.widget_24.setAcceptDrops(True)
        self.widget_24.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_24.setObjectName("widget_24")
        self.widget_51 = QtWidgets.QWidget(self.centralwidget)
        self.widget_51.setGeometry(QtCore.QRect(500, 370, 71, 71))
        self.widget_51.setAcceptDrops(True)
        self.widget_51.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_51.setObjectName("widget_51")
        self.widget_25 = QtWidgets.QWidget(self.centralwidget)
        self.widget_25.setGeometry(QtCore.QRect(430, 300, 71, 71))
        self.widget_25.setAcceptDrops(True)
        self.widget_25.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_25.setObjectName("widget_25")
        self.widget_26 = QtWidgets.QWidget(self.centralwidget)
        self.widget_26.setGeometry(QtCore.QRect(220, 300, 71, 71))
        self.widget_26.setAcceptDrops(True)
        self.widget_26.setStyleSheet("background-image: url(:/background.png);")
        self.widget_26.setObjectName("widget_26")
        self.widget_27 = QtWidgets.QWidget(self.centralwidget)
        self.widget_27.setGeometry(QtCore.QRect(360, 300, 71, 71))
        self.widget_27.setAcceptDrops(True)
        self.widget_27.setStyleSheet("background-image: url(:/background.png);")
        self.widget_27.setObjectName("widget_27")
        self.widget_52 = QtWidgets.QWidget(self.centralwidget)
        self.widget_52.setGeometry(QtCore.QRect(80, 370, 71, 71))
        self.widget_52.setAcceptDrops(True)
        self.widget_52.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_52.setObjectName("widget_52")
        self.widget_28 = QtWidgets.QWidget(self.centralwidget)
        self.widget_28.setGeometry(QtCore.QRect(80, 300, 71, 71))
        self.widget_28.setAcceptDrops(True)
        self.widget_28.setStyleSheet("background-image: url(:/background.png);")
        self.widget_28.setObjectName("widget_28")
        self.widget_53 = QtWidgets.QWidget(self.centralwidget)
        self.widget_53.setGeometry(QtCore.QRect(290, 370, 71, 71))
        self.widget_53.setAcceptDrops(True)
        self.widget_53.setStyleSheet("background-image: url(:/background.png);")
        self.widget_53.setObjectName("widget_53")
        self.widget_29 = QtWidgets.QWidget(self.centralwidget)
        self.widget_29.setGeometry(QtCore.QRect(150, 300, 71, 71))
        self.widget_29.setAcceptDrops(True)
        self.widget_29.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_29.setObjectName("widget_29")
        self.widget_54 = QtWidgets.QWidget(self.centralwidget)
        self.widget_54.setGeometry(QtCore.QRect(430, 370, 71, 71))
        self.widget_54.setAcceptDrops(True)
        self.widget_54.setStyleSheet("background-image: url(:/background.png);")
        self.widget_54.setObjectName("widget_54")
        self.widget_30 = QtWidgets.QWidget(self.centralwidget)
        self.widget_30.setGeometry(QtCore.QRect(500, 300, 71, 71))
        self.widget_30.setAcceptDrops(True)
        self.widget_30.setStyleSheet("background-image: url(:/background.png);")
        self.widget_30.setObjectName("widget_30")
        self.widget_55 = QtWidgets.QWidget(self.centralwidget)
        self.widget_55.setGeometry(QtCore.QRect(10, 370, 71, 71))
        self.widget_55.setAcceptDrops(True)
        self.widget_55.setStyleSheet("background-image: url(:/background.png);")
        self.widget_55.setObjectName("widget_55")
        self.widget_31 = QtWidgets.QWidget(self.centralwidget)
        self.widget_31.setGeometry(QtCore.QRect(290, 300, 71, 71))
        self.widget_31.setAcceptDrops(True)
        self.widget_31.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_31.setObjectName("widget_31")
        self.widget_56 = QtWidgets.QWidget(self.centralwidget)
        self.widget_56.setGeometry(QtCore.QRect(150, 370, 71, 71))
        self.widget_56.setAcceptDrops(True)
        self.widget_56.setStyleSheet("background-image: url(:/background.png);")
        self.widget_56.setObjectName("widget_56")
        self.widget_57 = QtWidgets.QWidget(self.centralwidget)
        self.widget_57.setGeometry(QtCore.QRect(360, 370, 71, 71))
        self.widget_57.setAcceptDrops(True)
        self.widget_57.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_57.setObjectName("widget_57")
        self.widget_58 = QtWidgets.QWidget(self.centralwidget)
        self.widget_58.setGeometry(QtCore.QRect(220, 370, 71, 71))
        self.widget_58.setAcceptDrops(True)
        self.widget_58.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_58.setObjectName("widget_58")
        self.widget_32 = QtWidgets.QWidget(self.centralwidget)
        self.widget_32.setGeometry(QtCore.QRect(10, 300, 71, 71))
        self.widget_32.setAcceptDrops(True)
        self.widget_32.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_32.setObjectName("widget_32")
        self.widget_59 = QtWidgets.QWidget(self.centralwidget)
        self.widget_59.setGeometry(QtCore.QRect(500, 510, 71, 71))
        self.widget_59.setAcceptDrops(True)
        self.widget_59.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_59.setObjectName("widget_59")

        self.widget_33 = QtWidgets.QWidget(self.centralwidget)
        self.widget_33.setGeometry(QtCore.QRect(430, 440, 71, 71))
        self.widget_33.setAcceptDrops(True)
        self.widget_33.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_33.setObjectName("widget_33")

        self.widget_34 = QtWidgets.QWidget(self.centralwidget)
        self.widget_34.setGeometry(QtCore.QRect(220, 440, 71, 71))
        self.widget_34.setAcceptDrops(True)
        self.widget_34.setStyleSheet("background-image: url(:/background.png);")
        self.widget_34.setObjectName("widget_34")

        self.widget_60 = QtWidgets.QWidget(self.centralwidget)
        self.widget_60.setGeometry(QtCore.QRect(360, 440, 71, 71))
        self.widget_60.setAcceptDrops(True)
        self.widget_60.setStyleSheet("background-image: url(:/background.png);")
        self.widget_60.setObjectName("widget_60")

        self.widget_61 = QtWidgets.QWidget(self.centralwidget)
        self.widget_61.setGeometry(QtCore.QRect(80, 510, 71, 71))
        self.widget_61.setAcceptDrops(True)
        self.widget_61.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_61.setObjectName("widget_61")

        self.widget_62 = QtWidgets.QWidget(self.centralwidget)
        self.widget_62.setGeometry(QtCore.QRect(80, 440, 71, 71))
        self.widget_62.setAcceptDrops(True)
        self.widget_62.setStyleSheet("background-image: url(:/background.png);")
        self.widget_62.setObjectName("widget_62")

        self.widget_63 = QtWidgets.QWidget(self.centralwidget)
        self.widget_63.setGeometry(QtCore.QRect(290, 510, 71, 71))
        self.widget_63.setAcceptDrops(True)
        self.widget_63.setStyleSheet("background-image: url(:/background.png);")
        self.widget_63.setObjectName("widget_63")

        self.widget_64 = QtWidgets.QWidget(self.centralwidget)
        self.widget_64.setGeometry(QtCore.QRect(150, 440, 71, 71))
        self.widget_64.setAcceptDrops(True)
        self.widget_64.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_64.setObjectName("widget_64")

        self.widget_65 = QtWidgets.QWidget(self.centralwidget)
        self.widget_65.setGeometry(QtCore.QRect(430, 510, 71, 71))
        self.widget_65.setAcceptDrops(True)
        self.widget_65.setStyleSheet("background-image: url(:/background.png);")
        self.widget_65.setObjectName("widget_65")

        self.widget_66 = QtWidgets.QWidget(self.centralwidget)
        self.widget_66.setGeometry(QtCore.QRect(500, 440, 71, 71))
        self.widget_66.setAcceptDrops(True)
        self.widget_66.setStyleSheet("background-image: url(:/background.png);")
        self.widget_66.setObjectName("widget_66")

        self.widget_67 = QtWidgets.QWidget(self.centralwidget)
        self.widget_67.setGeometry(QtCore.QRect(10, 510, 71, 71))
        self.widget_67.setAcceptDrops(True)
        self.widget_67.setStyleSheet("background-image: url(:/background.png);")
        self.widget_67.setObjectName("widget_67")

        self.widget_68 = QtWidgets.QWidget(self.centralwidget)
        self.widget_68.setGeometry(QtCore.QRect(290, 440, 71, 71))
        self.widget_68.setAcceptDrops(True)
        self.widget_68.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_68.setObjectName("widget_68")

        self.widget_69 = QtWidgets.QWidget(self.centralwidget)
        self.widget_69.setGeometry(QtCore.QRect(150, 510, 71, 71))
        self.widget_69.setAcceptDrops(True)
        self.widget_69.setStyleSheet("background-image: url(:/background.png);")
        self.widget_69.setObjectName("widget_69")

        self.widget_70 = QtWidgets.QWidget(self.centralwidget)
        self.widget_70.setGeometry(QtCore.QRect(360, 510, 71, 71))
        self.widget_70.setAcceptDrops(True)
        self.widget_70.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_70.setObjectName("widget_70")

        self.widget_71 = QtWidgets.QWidget(self.centralwidget)
        self.widget_71.setGeometry(QtCore.QRect(220, 510, 71, 71))
        self.widget_71.setAcceptDrops(True)
        self.widget_71.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_71.setObjectName("widget_71")

        self.widget_72 = QtWidgets.QWidget(self.centralwidget)
        self.widget_72.setGeometry(QtCore.QRect(10, 440, 71, 71))
        self.widget_72.setAcceptDrops(True)
        self.widget_72.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_72.setObjectName("widget_72")



        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

    def flip_board_icons(self):

        # Black pawns
        self.white_pawn_icon1.move(self.list_values_x[0], self.list_values_y[1])
        self.white_pawn_icon1.show()
        self.white_pawn_icon1.setAttribute(Qt.WA_DeleteOnClose)

        self.white_pawn_icon2.move(self.list_values_x[1], self.list_values_y[1])
        self.white_pawn_icon2.show()
        self.white_pawn_icon2.setAttribute(Qt.WA_DeleteOnClose)

        self.white_pawn_icon3.move(self.list_values_x[2], self.list_values_y[1])
        self.white_pawn_icon3.show()
        self.white_pawn_icon3.setAttribute(Qt.WA_DeleteOnClose)

        self.white_pawn_icon4.move(self.list_values_x[3], self.list_values_y[1])
        self.white_pawn_icon4.show()
        self.white_pawn_icon4.setAttribute(Qt.WA_DeleteOnClose)

        self.white_pawn_icon5.move(self.list_values_x[4], self.list_values_y[1])
        self.white_pawn_icon5.show()
        self.white_pawn_icon5.setAttribute(Qt.WA_DeleteOnClose)

        self.white_pawn_icon6.move(self.list_values_x[5], self.list_values_y[1])
        self.white_pawn_icon6.show()
        self.white_pawn_icon6.setAttribute(Qt.WA_DeleteOnClose)

        self.white_pawn_icon7.move(self.list_values_x[6], self.list_values_y[1])
        self.white_pawn_icon7.show()
        self.white_pawn_icon7.setAttribute(Qt.WA_DeleteOnClose)

        self.white_pawn_icon8.move(self.list_values_x[7], self.list_values_y[1])
        self.white_pawn_icon8.show()
        self.white_pawn_icon8.setAttribute(Qt.WA_DeleteOnClose)

        # White pawns

        self.black_pawn_icon1.move(self.list_values_x[0],  self.list_values_y[6])
        self.black_pawn_icon1.show()
        self.black_pawn_icon1.setAttribute(Qt.WA_DeleteOnClose)

        self.black_pawn_icon2.move(self.list_values_x[1],  self.list_values_y[6])
        self.black_pawn_icon2.show()
        self.black_pawn_icon2.setAttribute(Qt.WA_DeleteOnClose)

        self.black_pawn_icon3.move(self.list_values_x[2],  self.list_values_y[6])
        self.black_pawn_icon3.show()
        self.black_pawn_icon3.setAttribute(Qt.WA_DeleteOnClose)

        self.black_pawn_icon4.move(self.list_values_x[3],  self.list_values_y[6])
        self.black_pawn_icon4.show()
        self.black_pawn_icon4.setAttribute(Qt.WA_DeleteOnClose)

        self.black_pawn_icon5.move(self.list_values_x[4],  self.list_values_y[6])
        self.black_pawn_icon5.show()
        self.black_pawn_icon5.setAttribute(Qt.WA_DeleteOnClose)

        self.black_pawn_icon6.move(self.list_values_x[5],  self.list_values_y[6])
        self.black_pawn_icon6.show()
        self.black_pawn_icon6.setAttribute(Qt.WA_DeleteOnClose)

        self.black_pawn_icon7.move(self.list_values_x[6],  self.list_values_y[6])
        self.black_pawn_icon7.show()
        self.black_pawn_icon7.setAttribute(Qt.WA_DeleteOnClose)

        self.black_pawn_icon8.move(self.list_values_x[7],  self.list_values_y[6])
        self.black_pawn_icon8.show()
        self.black_pawn_icon8.setAttribute(Qt.WA_DeleteOnClose)

        # Black rook

        self.white_rook_icon1.move(self.list_values_x[0],  self.list_values_y[0])
        self.white_rook_icon1.show()
        self.white_rook_icon1.setAttribute(Qt.WA_DeleteOnClose)

        self.white_rook_icon2.move(self.list_values_x[7],  self.list_values_y[0])
        self.white_rook_icon2.show()
        self.white_rook_icon2.setAttribute(Qt.WA_DeleteOnClose)

        # white rook

        self.black_rook_icon1.move(self.list_values_x[0],  self.list_values_y[7])
        self.black_rook_icon1.show()
        self.black_rook_icon1.setAttribute(Qt.WA_DeleteOnClose)

        self.black_rook_icon2.move(self.list_values_x[7],  self.list_values_y[7])
        self.black_rook_icon2.show()
        self.black_rook_icon2.setAttribute(Qt.WA_DeleteOnClose)

        # Black knight

        self.white_knight_icon1.move(self.list_values_x[1],  self.list_values_y[0])
        self.white_knight_icon1.show()
        self.white_knight_icon1.setAttribute(Qt.WA_DeleteOnClose)

        self.white_knight_icon2.move(self.list_values_x[6],  self.list_values_y[0])
        self.white_knight_icon2.show()
        self.white_knight_icon2.setAttribute(Qt.WA_DeleteOnClose)

        # white knight

        self.black_knight_icon1.move(self.list_values_x[1], self.list_values_y[7])
        self.black_knight_icon1.show()
        self.black_knight_icon1.setAttribute(Qt.WA_DeleteOnClose)

        self.black_knight_icon2.move(self.list_values_x[6],  self.list_values_y[7])
        self.black_knight_icon2.show()
        self.black_knight_icon2.setAttribute(Qt.WA_DeleteOnClose)

        # Black bishop

        self.white_bishop_icon1.move(self.list_values_x[2], self.list_values_y[0])
        self.white_bishop_icon1.show()
        self.white_bishop_icon1.setAttribute(Qt.WA_DeleteOnClose)

        self.white_bishop_icon2.move(self.list_values_x[5], self.list_values_y[0])
        self.white_bishop_icon2.show()
        self.white_bishop_icon2.setAttribute(Qt.WA_DeleteOnClose)

        # white bishop

        self.black_bishop_icon1.move(self.list_values_x[2], self.list_values_y[7])
        self.black_bishop_icon1.show()
        self.black_bishop_icon1.setAttribute(Qt.WA_DeleteOnClose)

        self.black_bishop_icon2.move(self.list_values_x[5], self.list_values_y[7])
        self.black_bishop_icon2.show()
        self.black_bishop_icon2.setAttribute(Qt.WA_DeleteOnClose)

        # Black queen

        self.white_queen_icon.move(self.list_values_x[4], self.list_values_y[0])
        self.white_queen_icon.show()
        self.white_queen_icon.setAttribute(Qt.WA_DeleteOnClose)

        # white queen

        self.black_queen_icon.move(self.list_values_x[4], self.list_values_y[7])
        self.black_queen_icon.show()
        self.black_queen_icon.setAttribute(Qt.WA_DeleteOnClose)

        # Black king

        self.white_king_icon.move(self.list_values_x[3], self.list_values_y[0])
        self.white_king_icon.show()
        self.white_king_icon.setAttribute(Qt.WA_DeleteOnClose)

        # white king

        self.black_king_icon.move(self.list_values_x[3], self.list_values_y[7])
        self.black_king_icon.show()
        self.black_king_icon.setAttribute(Qt.WA_DeleteOnClose)

    def create_board(self):

        self.black_knight_icon1 = QtWidgets.QLabel(self)
        self.black_knight_icon1.setGeometry(QtCore.QRect(self.list_values_x[1], self.list_values_y[0], 71, 71))
        self.black_knight_icon1.setObjectName("black_knight_icon1")

        self.black_knight_icon2 = QtWidgets.QLabel(self)
        self.black_knight_icon2.setGeometry(QtCore.QRect(self.list_values_x[6], self.list_values_y[0], 71, 71))
        self.black_knight_icon2.setObjectName("black_knight_icon2")

        self.black_queen_icon = QtWidgets.QLabel(self)
        self.black_queen_icon.setGeometry(QtCore.QRect(0, 0, 71, 71))
        self.black_queen_icon.setObjectName("black_queen_icon")

        self.black_bishop_icon1 = QtWidgets.QLabel(self)
        self.black_bishop_icon1.setGeometry(QtCore.QRect(self.list_values_x[2], self.list_values_y[0], 71, 71))
        self.black_bishop_icon1.setObjectName("black_bishop_icon1")

        self.black_rook_icon1 = QtWidgets.QLabel(self)
        self.black_rook_icon1.setGeometry(QtCore.QRect(self.list_values_x[0], self.list_values_y[0], 71, 71))
        self.black_rook_icon1.setObjectName("black_rook_icon1")

        self.black_rook_icon2 = QtWidgets.QLabel(self)
        self.black_rook_icon2.setGeometry(QtCore.QRect(0, 0, 71, 71))
        self.black_rook_icon2.setObjectName("black_rook_icon2")

        self.black_bishop_icon2 = QtWidgets.QLabel(self)
        self.black_bishop_icon2.setGeometry(QtCore.QRect(0, 0, 71, 71))
        self.black_bishop_icon2.setObjectName("black_bishop_icon2")

        self.black_pawn_icon2 = QtWidgets.QLabel(self)
        self.black_pawn_icon2.setGeometry(QtCore.QRect(0, 0, 71, 71))
        self.black_pawn_icon2.setObjectName("black_pawn_icon2")

        self.black_pawn_icon1 = QtWidgets.QLabel(self)
        self.black_pawn_icon1.setGeometry(QtCore.QRect(0, 0, 71, 71))
        self.black_pawn_icon1.setObjectName("black_pawn_icon1")

        self.black_pawn_icon3 = QtWidgets.QLabel(self)
        self.black_pawn_icon3.setGeometry(QtCore.QRect(0, 0, 71, 71))
        self.black_pawn_icon3.setObjectName("black_pawn_icon3")

        self.black_pawn_icon4 = QtWidgets.QLabel(self)
        self.black_pawn_icon4.setGeometry(QtCore.QRect(0, 0, 71, 71))
        self.black_pawn_icon4.setObjectName("black_pawn_icon4")

        self.black_pawn_icon6 = QtWidgets.QLabel(self)
        self.black_pawn_icon6.setGeometry(QtCore.QRect(0, 0, 71, 71))
        self.black_pawn_icon6.setObjectName("black_pawn_icon6")

        self.black_pawn_icon5 = QtWidgets.QLabel(self)
        self.black_pawn_icon5.setGeometry(QtCore.QRect(0, 0, 71, 71))
        self.black_pawn_icon5.setObjectName("black_pawn_icon5")

        self.black_pawn_icon8 = QtWidgets.QLabel(self)
        self.black_pawn_icon8.setGeometry(QtCore.QRect(0, 0, 71, 71))
        self.black_pawn_icon8.setObjectName("black_pawn_icon8")

        self.black_pawn_icon7 = QtWidgets.QLabel(self)
        self.black_pawn_icon7.setGeometry(QtCore.QRect(0, 0, 71, 71))
        self.black_pawn_icon7.setObjectName("black_pawn_icon7")

        self.black_king_icon = QtWidgets.QLabel(self)
        self.black_king_icon.setGeometry(QtCore.QRect(0, 0, 71, 71))
        self.black_king_icon.setObjectName("black_king_icon")

        self.white_pawn_icon7 = QtWidgets.QLabel(self)
        self.white_pawn_icon7.setGeometry(QtCore.QRect(0, 0, 71, 71))
        self.white_pawn_icon7.setObjectName("white_pawn_icon7")

        self.white_pawn_icon4 = QtWidgets.QLabel(self)
        self.white_pawn_icon4.setGeometry(QtCore.QRect(0, 0, 71, 71))
        self.white_pawn_icon4.setObjectName("white_pawn_icon4")

        self.white_pawn_icon6 = QtWidgets.QLabel(self)
        self.white_pawn_icon6.setGeometry(QtCore.QRect(0, 0, 71, 71))
        self.white_pawn_icon6.setObjectName("white_pawn_icon6")

        self.white_knight_icon1 = QtWidgets.QLabel(self)
        self.white_knight_icon1.setGeometry(QtCore.QRect(0, 0, 71, 71))
        self.white_knight_icon1.setObjectName("white_knight_icon1")

        self.white_pawn_icon2 = QtWidgets.QLabel(self)
        self.white_pawn_icon2.setGeometry(QtCore.QRect(0, 0, 71, 71))
        self.white_pawn_icon2.setObjectName("white_pawn_icon2")

        self.white_king_icon = QtWidgets.QLabel(self)
        self.white_king_icon.setGeometry(QtCore.QRect(0, 0, 71, 71))
        self.white_king_icon.setObjectName("white_king_icon")

        self.white_pawn_icon3 = QtWidgets.QLabel(self)
        self.white_pawn_icon3.setGeometry(QtCore.QRect(0, 0, 71, 71))
        self.white_pawn_icon3.setObjectName("white_pawn_icon3")

        self.white_knight_icon2 = QtWidgets.QLabel(self)
        self.white_knight_icon2.setGeometry(QtCore.QRect(0, 0, 71, 71))
        self.white_knight_icon2.setObjectName("white_knight_icon2")

        self.white_pawn_icon8 = QtWidgets.QLabel(self)
        self.white_pawn_icon8.setGeometry(QtCore.QRect(0, 0, 71, 71))
        self.white_pawn_icon8.setObjectName("white_pawn_icon8")

        self.white_rook_icon1 = QtWidgets.QLabel(self)
        self.white_rook_icon1.setGeometry(QtCore.QRect(0, 0, 71, 71))
        self.white_rook_icon1.setObjectName("white_rook_icon1")

        self.white_rook_icon2 = QtWidgets.QLabel(self)
        self.white_rook_icon2.setGeometry(QtCore.QRect(0, 0, 71, 71))
        self.white_rook_icon2.setObjectName("white_rook_icon2")

        self.white_pawn_icon5 = QtWidgets.QLabel(self)
        self.white_pawn_icon5.setGeometry(QtCore.QRect(0, 0, 71, 71))
        self.white_pawn_icon5.setObjectName("white_pawn_icon5")

        self.white_bishop_icon1 = QtWidgets.QLabel(self)
        self.white_bishop_icon1.setGeometry(QtCore.QRect(0, 0, 71, 71))
        self.white_bishop_icon1.setObjectName("white_bishop_icon1")

        self.white_bishop_icon2 = QtWidgets.QLabel(self)
        self.white_bishop_icon2.setGeometry(QtCore.QRect(0, 0, 71, 71))
        self.white_bishop_icon2.setObjectName("white_bishop_icon2")

        self.white_queen_icon = QtWidgets.QLabel(self)
        self.white_queen_icon.setGeometry(QtCore.QRect(0, 0, 71, 71))
        self.white_queen_icon.setObjectName("white_queen_icon")

        self.white_pawn_icon1 = QtWidgets.QLabel(self)
        self.white_pawn_icon1.setGeometry(QtCore.QRect(0, 0, 71, 71))
        self.white_pawn_icon1.setObjectName("white_pawn_icon1")

        # Black pawns
        root = QFileInfo(__file__).absolutePath()
        image_black_pawn = QImage(root + '/iconos/black_pawn.png')
        self.black_pawn_icon1.setPixmap(
            QPixmap.fromImage(image_black_pawn).scaled(70, 70, Qt.IgnoreAspectRatio, Qt.SmoothTransformation))
        self.black_pawn_icon1.adjustSize()
        self.black_pawn_icon1.move(self.list_values_x[0], self.list_values_y[1])
        self.black_pawn_icon1.show()
        self.black_pawn_icon1.setAttribute(Qt.WA_DeleteOnClose)

        self.black_pawn_icon2.setPixmap(
            QPixmap.fromImage(image_black_pawn).scaled(70, 70, Qt.IgnoreAspectRatio, Qt.SmoothTransformation))
        self.black_pawn_icon2.adjustSize()
        self.black_pawn_icon2.move(self.list_values_x[1], self.list_values_y[1])
        self.black_pawn_icon2.show()
        self.black_pawn_icon2.setAttribute(Qt.WA_DeleteOnClose)

        self.black_pawn_icon3.setPixmap(
            QPixmap.fromImage(image_black_pawn).scaled(70, 70, Qt.IgnoreAspectRatio, Qt.SmoothTransformation))
        self.black_pawn_icon3.adjustSize()
        self.black_pawn_icon3.move(self.list_values_x[2], self.list_values_y[1])
        self.black_pawn_icon3.show()
        self.black_pawn_icon3.setAttribute(Qt.WA_DeleteOnClose)

        self.black_pawn_icon4.setPixmap(
            QPixmap.fromImage(image_black_pawn).scaled(70, 70, Qt.IgnoreAspectRatio, Qt.SmoothTransformation))
        self.black_pawn_icon4.adjustSize()
        self.black_pawn_icon4.move(self.list_values_x[3], self.list_values_y[1])
        self.black_pawn_icon4.show()
        self.black_pawn_icon4.setAttribute(Qt.WA_DeleteOnClose)

        self.black_pawn_icon5.setPixmap(
            QPixmap.fromImage(image_black_pawn).scaled(70, 70, Qt.IgnoreAspectRatio, Qt.SmoothTransformation))
        self.black_pawn_icon5.adjustSize()
        self.black_pawn_icon5.move(self.list_values_x[4], self.list_values_y[1])
        self.black_pawn_icon5.show()
        self.black_pawn_icon5.setAttribute(Qt.WA_DeleteOnClose)

        self.black_pawn_icon6.setPixmap(
            QPixmap.fromImage(image_black_pawn).scaled(70, 70, Qt.IgnoreAspectRatio, Qt.SmoothTransformation))
        self.black_pawn_icon6.adjustSize()
        self.black_pawn_icon6.move(self.list_values_x[5], self.list_values_y[1])
        self.black_pawn_icon6.show()
        self.black_pawn_icon6.setAttribute(Qt.WA_DeleteOnClose)

        self.black_pawn_icon7.setPixmap(
            QPixmap.fromImage(image_black_pawn).scaled(70, 70, Qt.IgnoreAspectRatio, Qt.SmoothTransformation))
        self.black_pawn_icon7.adjustSize()
        self.black_pawn_icon7.move(self.list_values_x[6], self.list_values_y[1])
        self.black_pawn_icon7.show()
        self.black_pawn_icon7.setAttribute(Qt.WA_DeleteOnClose)

        self.black_pawn_icon8.setPixmap(
            QPixmap.fromImage(image_black_pawn).scaled(70, 70, Qt.IgnoreAspectRatio, Qt.SmoothTransformation))
        self.black_pawn_icon8.adjustSize()
        self.black_pawn_icon8.move(self.list_values_x[7], self.list_values_y[1])
        self.black_pawn_icon8.show()
        self.black_pawn_icon8.setAttribute(Qt.WA_DeleteOnClose)

        # White pawns
        root = QFileInfo(__file__).absolutePath()
        image_white_pawn = QImage(root + '/iconos/white_pawn.png')
        self.white_pawn_icon1.setPixmap(
            QPixmap.fromImage(image_white_pawn).scaled(70, 70, Qt.IgnoreAspectRatio, Qt.SmoothTransformation))
        self.white_pawn_icon1.adjustSize()
        self.white_pawn_icon1.move(self.list_values_x[0], self.list_values_y[6])
        self.white_pawn_icon1.show()
        self.white_pawn_icon1.setAttribute(Qt.WA_DeleteOnClose)

        self.white_pawn_icon2.setPixmap(
            QPixmap.fromImage(image_white_pawn).scaled(70, 70, Qt.IgnoreAspectRatio, Qt.SmoothTransformation))
        self.white_pawn_icon2.adjustSize()
        self.white_pawn_icon2.move(self.list_values_x[1], self.list_values_y[6])
        self.white_pawn_icon2.show()
        self.white_pawn_icon2.setAttribute(Qt.WA_DeleteOnClose)

        self.white_pawn_icon3.setPixmap(
            QPixmap.fromImage(image_white_pawn).scaled(70, 70, Qt.IgnoreAspectRatio, Qt.SmoothTransformation))
        self.white_pawn_icon3.adjustSize()
        self.white_pawn_icon3.move(self.list_values_x[2], self.list_values_y[6])
        self.white_pawn_icon3.show()
        self.white_pawn_icon3.setAttribute(Qt.WA_DeleteOnClose)

        self.white_pawn_icon4.setPixmap(
            QPixmap.fromImage(image_white_pawn).scaled(70, 70, Qt.IgnoreAspectRatio, Qt.SmoothTransformation))
        self.white_pawn_icon4.adjustSize()
        self.white_pawn_icon4.move(self.list_values_x[3], self.list_values_y[6])
        self.white_pawn_icon4.show()
        self.white_pawn_icon4.setAttribute(Qt.WA_DeleteOnClose)

        self.white_pawn_icon5.setPixmap(
            QPixmap.fromImage(image_white_pawn).scaled(70, 70, Qt.IgnoreAspectRatio, Qt.SmoothTransformation))
        self.white_pawn_icon5.adjustSize()
        self.white_pawn_icon5.move(self.list_values_x[4], self.list_values_y[6])
        self.white_pawn_icon5.show()
        self.white_pawn_icon5.setAttribute(Qt.WA_DeleteOnClose)

        self.white_pawn_icon6.setPixmap(
            QPixmap.fromImage(image_white_pawn).scaled(70, 70, Qt.IgnoreAspectRatio, Qt.SmoothTransformation))
        self.white_pawn_icon6.adjustSize()
        self.white_pawn_icon6.move(self.list_values_x[5], self.list_values_y[6])
        self.white_pawn_icon6.show()
        self.white_pawn_icon6.setAttribute(Qt.WA_DeleteOnClose)

        self.white_pawn_icon7.setPixmap(
            QPixmap.fromImage(image_white_pawn).scaled(70, 70, Qt.IgnoreAspectRatio, Qt.SmoothTransformation))
        self.white_pawn_icon7.adjustSize()
        self.white_pawn_icon7.move(self.list_values_x[6], self.list_values_y[6])
        self.white_pawn_icon7.show()
        self.white_pawn_icon7.setAttribute(Qt.WA_DeleteOnClose)

        self.white_pawn_icon8.setPixmap(
            QPixmap.fromImage(image_white_pawn).scaled(70, 70, Qt.IgnoreAspectRatio, Qt.SmoothTransformation))
        self.white_pawn_icon8.adjustSize()
        self.white_pawn_icon8.move(self.list_values_x[7], self.list_values_y[6])
        self.white_pawn_icon8.show()
        self.white_pawn_icon8.setAttribute(Qt.WA_DeleteOnClose)

        # Black rook
        root = QFileInfo(__file__).absolutePath()
        image_black_rook = QImage(root + '/iconos/black_rook.png')
        self.black_rook_icon1.setPixmap(
            QPixmap.fromImage(image_black_rook).scaled(70, 70, Qt.IgnoreAspectRatio, Qt.SmoothTransformation))
        self.black_rook_icon1.adjustSize()
        self.black_rook_icon1.move(self.list_values_x[0], self.list_values_y[0])
        self.black_rook_icon1.show()
        self.black_rook_icon1.setAttribute(Qt.WA_DeleteOnClose)

        self.black_rook_icon2.setPixmap(
            QPixmap.fromImage(image_black_rook).scaled(70, 70, Qt.IgnoreAspectRatio, Qt.SmoothTransformation))
        self.black_rook_icon2.adjustSize()
        self.black_rook_icon2.move(self.list_values_x[7], self.list_values_y[0])
        self.black_rook_icon2.show()
        self.black_rook_icon2.setAttribute(Qt.WA_DeleteOnClose)

        # white rook
        root = QFileInfo(__file__).absolutePath()
        image_white_rook = QImage(root + '/iconos/white_rook.png')
        self.white_rook_icon1.setPixmap(
            QPixmap.fromImage(image_white_rook).scaled(70, 70, Qt.IgnoreAspectRatio, Qt.SmoothTransformation))
        self.white_rook_icon1.adjustSize()
        self.white_rook_icon1.move(self.list_values_x[0], self.list_values_y[7])
        self.white_rook_icon1.show()
        self.white_rook_icon1.setAttribute(Qt.WA_DeleteOnClose)

        self.white_rook_icon2.setPixmap(
            QPixmap.fromImage(image_white_rook).scaled(70, 70, Qt.IgnoreAspectRatio, Qt.SmoothTransformation))
        self.white_rook_icon2.adjustSize()
        self.white_rook_icon2.move(self.list_values_x[7], self.list_values_y[7])
        self.white_rook_icon2.show()
        self.white_rook_icon2.setAttribute(Qt.WA_DeleteOnClose)

        # Black knight
        root = QFileInfo(__file__).absolutePath()
        image_black_knight = QImage(root + '/iconos/black_knight.png')
        self.black_knight_icon1.setPixmap(
            QPixmap.fromImage(image_black_knight).scaled(70, 70, Qt.IgnoreAspectRatio, Qt.SmoothTransformation))
        self.black_knight_icon1.adjustSize()
        self.black_knight_icon1.move(self.list_values_x[1], self.list_values_y[0])
        self.black_knight_icon1.show()
        self.black_knight_icon1.setAttribute(Qt.WA_DeleteOnClose)

        self.black_knight_icon2.setPixmap(
            QPixmap.fromImage(image_black_knight).scaled(70, 70, Qt.IgnoreAspectRatio, Qt.SmoothTransformation))
        self.black_knight_icon2.adjustSize()
        self.black_knight_icon2.move(self.list_values_x[6], self.list_values_y[0])
        self.black_knight_icon2.show()
        self.black_knight_icon2.setAttribute(Qt.WA_DeleteOnClose)

        # white knight
        root = QFileInfo(__file__).absolutePath()
        image_white_knight = QImage(root + '/iconos/white_knight.png')
        self.white_knight_icon1.setPixmap(
            QPixmap.fromImage(image_white_knight).scaled(70, 70, Qt.IgnoreAspectRatio, Qt.SmoothTransformation))
        self.white_knight_icon1.adjustSize()
        self.white_knight_icon1.move(self.list_values_x[1], self.list_values_y[7])
        self.white_knight_icon1.show()
        self.white_knight_icon1.setAttribute(Qt.WA_DeleteOnClose)

        self.white_knight_icon2.setPixmap(
            QPixmap.fromImage(image_white_knight).scaled(70, 70, Qt.IgnoreAspectRatio, Qt.SmoothTransformation))
        self.white_knight_icon2.adjustSize()
        self.white_knight_icon2.move(self.list_values_x[6], self.list_values_y[7])
        self.white_knight_icon2.show()
        self.white_knight_icon2.setAttribute(Qt.WA_DeleteOnClose)

        # Black bishop
        root = QFileInfo(__file__).absolutePath()
        image_black_bishop = QImage(root + '/iconos/black_bishop.png')
        self.black_bishop_icon1.setPixmap(
            QPixmap.fromImage(image_black_bishop).scaled(70, 70, Qt.IgnoreAspectRatio, Qt.SmoothTransformation))
        self.black_bishop_icon1.adjustSize()
        self.black_bishop_icon1.move(self.list_values_x[2], self.list_values_y[0])
        self.black_bishop_icon1.show()
        self.black_bishop_icon1.setAttribute(Qt.WA_DeleteOnClose)

        self.black_bishop_icon2.setPixmap(
            QPixmap.fromImage(image_black_bishop).scaled(70, 70, Qt.IgnoreAspectRatio, Qt.SmoothTransformation))
        self.black_bishop_icon2.adjustSize()
        self.black_bishop_icon2.move(self.list_values_x[5], self.list_values_y[0])
        self.black_bishop_icon2.show()
        self.black_bishop_icon2.setAttribute(Qt.WA_DeleteOnClose)

        # white bishop
        root = QFileInfo(__file__).absolutePath()
        image_white_bishop = QImage(root + '/iconos/white_bishop.png')
        self.white_bishop_icon1.setPixmap(
            QPixmap.fromImage(image_white_bishop).scaled(70, 70, Qt.IgnoreAspectRatio, Qt.SmoothTransformation))
        self.white_bishop_icon1.adjustSize()
        self.white_bishop_icon1.move(self.list_values_x[2], self.list_values_y[7])
        self.white_bishop_icon1.show()
        self.white_bishop_icon1.setAttribute(Qt.WA_DeleteOnClose)

        self.white_bishop_icon2.setPixmap(
            QPixmap.fromImage(image_white_bishop).scaled(70, 70, Qt.IgnoreAspectRatio, Qt.SmoothTransformation))
        self.white_bishop_icon2.adjustSize()
        self.white_bishop_icon2.move(self.list_values_x[5], self.list_values_y[7])
        self.white_bishop_icon2.show()
        self.white_bishop_icon2.setAttribute(Qt.WA_DeleteOnClose)

        # Black queen
        root = QFileInfo(__file__).absolutePath()
        image_black_queen = QImage(root + '/iconos/black_queen.png')
        self.black_queen_icon.setPixmap(
            QPixmap.fromImage(image_black_queen).scaled(70, 70, Qt.IgnoreAspectRatio, Qt.SmoothTransformation))
        self.black_queen_icon.adjustSize()
        self.black_queen_icon.move(self.list_values_x[3], self.list_values_y[0])
        self.black_queen_icon.show()
        self.black_queen_icon.setAttribute(Qt.WA_DeleteOnClose)

        # white queen
        root = QFileInfo(__file__).absolutePath()
        image_white_queen = QImage(root + '/iconos/white_queen.png')
        self.white_queen_icon.setPixmap(
            QPixmap.fromImage(image_white_queen).scaled(70, 70, Qt.IgnoreAspectRatio, Qt.SmoothTransformation))
        self.white_queen_icon.adjustSize()
        self.white_queen_icon.move(self.list_values_x[3], self.list_values_y[7])
        self.white_queen_icon.show()
        self.white_queen_icon.setAttribute(Qt.WA_DeleteOnClose)

        # Black king
        root = QFileInfo(__file__).absolutePath()
        image_black_king = QImage(root + '/iconos/black_king.png')
        self.black_king_icon.setPixmap(
            QPixmap.fromImage(image_black_king).scaled(70, 70, Qt.IgnoreAspectRatio, Qt.SmoothTransformation))
        self.black_king_icon.adjustSize()
        self.black_king_icon.move(self.list_values_x[4], self.list_values_y[0])
        self.black_king_icon.show()
        self.black_king_icon.setAttribute(Qt.WA_DeleteOnClose)

        # white king
        root = QFileInfo(__file__).absolutePath()
        image_white_king = QImage(root + '/iconos/white_king.png')
        self.white_king_icon.setPixmap(
            QPixmap.fromImage(image_white_king).scaled(70, 70, Qt.IgnoreAspectRatio, Qt.SmoothTransformation))
        self.white_king_icon.adjustSize()
        self.white_king_icon.move(self.list_values_x[4], self.list_values_y[7])
        self.white_king_icon.show()
        self.white_king_icon.setAttribute(Qt.WA_DeleteOnClose)

import icons_rc


