# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'youtube_engine.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_Engine(object):
    def setupUi(self, MainWindow_Engine):
        MainWindow_Engine.setObjectName("MainWindow_Engine")
        MainWindow_Engine.resize(497, 290)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/MainEngine32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow_Engine.setWindowIcon(icon)
        MainWindow_Engine.setStyleSheet("\n"
"\n"
"QLabel{background-color: rgb(255, 255, 255);}\n"
"QMainWindow{background-image: url(:/back.png);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow_Engine)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 40, 91, 31))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 170, 0);\n"
"border-radius: 10px;\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 100, 91, 31))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 170, 0);\n"
"border-radius: 10px")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 160, 91, 31))
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"color: rgb(0, 170, 0);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(260, 100, 91, 31))
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"color: rgb(0, 170, 0);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(260, 40, 91, 31))
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"color: rgb(0, 170, 0);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(290, 190, 91, 31))
        self.toolButton.setStyleSheet("QToolButton::hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(170, 255, 0);\n"
"}\n"
"QToolButton{background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 170, 0);\n"
"border-radius: 10px;\n"
"font: 75 8pt \"MS Shell Dlg 2\";}\n"
"\n"
"\n"
"")
        self.toolButton.setObjectName("toolButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(370, 100, 101, 31))
        self.lineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(140, 40, 101, 31))
        self.lineEdit_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(140, 100, 101, 31))
        self.lineEdit_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px")
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(140, 160, 101, 31))
        self.lineEdit_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px")
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(370, 40, 101, 31))
        self.lineEdit_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px")
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")
        MainWindow_Engine.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_Engine)
        self.statusbar.setObjectName("statusbar")
        MainWindow_Engine.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_Engine)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_Engine)

    def retranslateUi(self, MainWindow_Engine):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_Engine.setWindowTitle(_translate("MainWindow_Engine", "MainWindow"))
        self.label.setText(_translate("MainWindow_Engine", "     Skill Level"))
        self.label_2.setText(_translate("MainWindow_Engine", "Elo"))
        self.label_3.setText(_translate("MainWindow_Engine", "Depth"))
        self.label_4.setText(_translate("MainWindow_Engine", "Hash"))
        self.label_5.setText(_translate("MainWindow_Engine", "Threads"))
        self.toolButton.setText(_translate("MainWindow_Engine", "Aceptar"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow_Engine", "max: 300000"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow_Engine", "max: 40"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow_Engine", "max: 2850"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow_Engine", "max: 40"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow_Engine", "max: 50"))
import icons_rc
